[package]
name = "naming"
version = "0.1.0"
authors = ["Boholder <boholder@anche.no>"]
description = """
A command line tool to convert the naming format (case | notation) of identifiers.
Use this library to extract the keywords used to further match the source code files.
For working with sourcecode-related shell scripts.
"""
documentation = "https://github.com/boholder/naming"
homepage = "https://github.com/boholder/naming"
repository = "https://github.com/boholder/naming"
keywords = ["source", "code", "naming", "format"]
categories = ["command-line-utilities", "text-processing"]
license = "MIT"
edition = "2018"

[[bin]]
name = "naming"
path = "crates/cli/main.rs"
bench = false

[workspace]
members = [
    "crates/naming_lib",
]

[dependencies]
clap = "2.33.3"

[profile.release]
debug = 1